stages:
  - build
  - deploy

variables:
  DOCKER_TLS_CERTDIR: ""

build:
  stage: build
  image: node:18
  script:
    - yarn install
    - CI=false yarn build
    - mkdir -p build_output
    - cp -r build/* build_output/
  artifacts:
    paths:
      - build_output
      - deploy.sh
  tags:
    - docker


deploy:
  stage: deploy
  script:
    - pwd  # 현재 작업 디렉토리 확인
    - ls -la  # 현재 디렉토리 내용 확인
    - chmod +x deploy.sh
    - sh deploy.sh
  only:
    - main
  tags:
    - docker