stages:
  - pull
  - build
  - deploy

before_script:
  - cd $PROJECT_PATH

pull:
  stage: pull
  script:
    - cd aripay/DevCoop-front
    - git pull

build:
  stage: build
  script:
    - cd docker-composes
    - docker-compose -f docker-compose.aripay.yml build aripay-front

deploy:
  stage: deploy
  script:
    - cd docker-composes
    - docker-compose -f docker-compose.aripay.yml up -d aripay-front
  only:
    - main
