stages:
  - pull
  - build
  - deploy

before_script:
    - cd $DOCKER_COMPOSE_PATH

pull:
  stage: pull
  script:
    - docker-compose -f docker-compose.aripay.yml stop aripay-back
    - cd $PROJECT_PATH
    - git pull

build:
  stage: build
  script:
    - cd $DOCKER_COMPOSE_PATH
    - docker-compose -f docker-compose.aripay.yml build --no-cache aripay-back

deploy:
  stage: deploy
  script:
    - cd $DOCKER_COMPOSE_PATH
    - docker-compose -f docker-compose.aripay.yml up -d aripay-back
  only:
    - main
