ARG BASE_IMAGE=node:20-alpine

# Build stage
FROM ${BASE_IMAGE} AS builder
WORKDIR /app

ARG REACT_APP_API_URL
ARG REACT_APP_DEV_MODE=false
ARG REACT_APP_MOCK_IDENTITY_VERIFICATION=false
ARG REACT_APP_USE_MOCK_DATA=false
ARG REACT_APP_STORE_ID
ARG REACT_APP_CHANNEL_KEY_PAY
ARG REACT_APP_CHANNEL_KEY_AUTH

ENV REACT_APP_API_URL=$REACT_APP_API_URL
ENV REACT_APP_DEV_MODE=$REACT_APP_DEV_MODE
ENV REACT_APP_MOCK_IDENTITY_VERIFICATION=$REACT_APP_MOCK_IDENTITY_VERIFICATION
ENV REACT_APP_USE_MOCK_DATA=$REACT_APP_USE_MOCK_DATA
ENV REACT_APP_STORE_ID=$REACT_APP_STORE_ID
ENV REACT_APP_CHANNEL_KEY_PAY=$REACT_APP_CHANNEL_KEY_PAY
ENV REACT_APP_CHANNEL_KEY_AUTH=$REACT_APP_CHANNEL_KEY_AUTH

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .
RUN yarn build

# Runner stage
FROM nginx:1.27-alpine AS runner

COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
