FROM nginx:1.27-alpine

ARG REACT_APP_API_URL
ARG REACT_APP_DEV_MODE=false
ARG REACT_APP_MOCK_IDENTITY_VERIFICATION=false
ARG REACT_APP_USE_MOCK_DATA=false
ARG REACT_APP_STORE_ID
ARG REACT_APP_CHANNEL_KEY_PAY
ARG REACT_APP_CHANNEL_KEY_AUTH

COPY build/ /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
